<a href="https://colab.research.google.com/github/Sandyon1top/AI/blob/main/Sandip_dhakal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 3.1 – Python Version Check

In [ ]:
import sys
if sys.version_info.major == 3 and sys.version_info.minor >= 8:
    print("Hello, Python!")
    print(f"Python version: {sys.version}")
else:
    print("Please use Python 3.8 or higher.")

Hello, Python!
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


## 3.2 – Mutable vs Immutable

In [ ]:
# Mutable (List)
my_list = [10, 20, 30]
print("Original List:", my_list)
my_list.append(40)
print("Modified List:", my_list)

# Immutable (Tuple)
my_tuple = (10, 20, 30)
print("Original Tuple:", my_tuple)
# my_tuple.append(40)  # Uncommenting raises AttributeError

Original List: [10, 20, 30]
Modified List: [10, 20, 30, 40]
Original Tuple: (10, 20, 30)


### 3.2.1 – Numeric Types

In [ ]:
age = 31
pi = 3.14159
temperature = -12.3
print("data type of variable age =", type(age))
print("data type of variable pi =", type(pi))
print("data type of variable temperature =", type(temperature))

data type of variable age = <class 'int'>
data type of variable pi = <class 'float'>
data type of variable temperature = <class 'float'>


### 3.2.1 – String

In [ ]:
name = "Robert"
greeting = "Hi there"
address = "456 Elm Street"
print("data type of variable name =", type(name))
print("data type of variable greeting =", type(greeting))
print("data type of variable address =", type(address))
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])
print("The second to fourth letter:", name[1:4])
print("The first two letters:", name[:2])
print("Substring from third letter:", name[2:])

data type of variable name = <class 'str'>
data type of variable greeting = <class 'str'>
data type of variable address = <class 'str'>
The first letter of the name is: R
The last letter of the name is: t
The second to fourth letter: obe
The first two letters: Ro
Substring from third letter: bert


### 3.2.1 – List

In [ ]:
list1 = [5, 10, 15, 20]
mixed_list = [99, "World", False]
mixed_list[0] = True
print(mixed_list)

[True, 'World', False]


### 3.2.1 – Tuple

In [ ]:
colors = ('orange', 'purple', 'pink', 'white')
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])
# colors[0] = 'black'  # Raises TypeError - tuple is immutable

First element: orange
Last two elements: ('pink', 'white')
Middle two elements: ('purple', 'pink')


### 3.2.1 – Dict

In [ ]:
person = {'name': 'Maria', 'age': 27, 'city': 'Barcelona'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live in {person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is Maria. I am 27 years old and I live in Barcelona.
All keys: ['name', 'age', 'city']
All values: ['Maria', 27, 'Barcelona']


### 3.2.1 – Set

In [ ]:
unique_numbers = {2, 4, 6, 6, 8, 8, 10}
print(unique_numbers)

{2, 4, 6, 8, 10}


### 3.2.1 – Boolean

In [ ]:
is_teacher = False
has_passport = True
print("data type of variable is_teacher =", type(is_teacher))
print("data type of variable has_passport =", type(has_passport))

data type of variable is_teacher = <class 'bool'>
data type of variable has_passport = <class 'bool'>


### 3.2.1 – NoneType

In [ ]:
output = None
print(output)
print(type(output))

None
<class 'NoneType'>


## 3.4 – if-elif-else

In [ ]:
num = -7
if num > 0:
    print("Positive")
elif num == 0:
    print("Zero")
else:
    print("Negative")

Negative


## 3.4 – Comparison Operators

In [ ]:
x = 8
y = 15
if x > 0 and y < 50:
    print("Both conditions are true")
if x > 0 or y > 100:
    print("At least one condition is true")
if not x == 5:
    print("x is not equal to 5")

Both conditions are true
At least one condition is true
x is not equal to 5


## 3.4 – Logical Operators

In [ ]:
a = False
b = True

if a and b:
    print("Both a and b are True")
else:
    print("Either a or b is False")

if a or b:
    print("At least one of a or b is True")
else:
    print("Both a and b are False")

if not b:
    print("b is False")
else:
    print("b is True")

Either a or b is False
At least one of a or b is True
b is True


## 3.4.1 – Loops

In [ ]:
# for loop
vegetables = ["carrot", "broccoli", "spinach"]
for veg in vegetables:
    print(veg)

# while loop
count = 0
while count < 8:
    print("Count is:", count)
    count += 1

# break
vegetables = ["carrot", "broccoli", "spinach"]
print("loop 1")
for veg in vegetables:
    print(veg)
    if veg == "carrot":
        break

# continue
print("loop 2")
for veg in vegetables:
    if veg == "carrot":
        continue
    else:
        print(veg)

carrot
broccoli
spinach
Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4
Count is: 5
Count is: 6
Count is: 7
loop 1
carrot
loop 2
broccoli
spinach


## 3.6 – Well-structured Function (Docstring Example)

In [ ]:
def add_octal(a, b):
    '''
    Returns the sum of two decimal numbers in octal digits.
    Parameters:
        a (int): A decimal integer
        b (int): Another decimal integer
    Returns:
        octal_sum (str): Octal string of the sum of a and b
    '''
    octal_sum = oct(a + b)[2:]
    return octal_sum

print(add_octal(7, 9))

20


## 3.6.1 – Built-in Functions

In [ ]:
print("Goodbye, World!")
length = len("Python")
data_type = type(3.14)
total = sum([4, 5, 6, 7])
print(length, data_type, total)

Goodbye, World!
6 <class 'float'> 22


## 3.6.2 – Built-in Methods

In [ ]:
# str.upper()
message = "goodbye".upper()
print(message)

# list.append()
vegs = ["carrot", "broccoli"]
vegs.append("spinach")
print(vegs)

# dict.get()
info = {"name": "Bob", "age": 40}
age = info.get("name")
print(age)

GOODBYE
['carrot', 'broccoli', 'spinach']
Bob


## 3.6.3 – User-Defined Function

In [ ]:
def speed_converter():
    """
    Converts speed between km/h and mph.
    Prompts the user for conversion direction and value,
    then calculates and returns the converted speed.

    Returns:
        float: The converted speed value.
    """
    print("Choose conversion type:")
    print("1. km/h to mph")
    print("2. mph to km/h")

    choice = input("Enter 1 or 2: ")

    if choice == "1":
        kmh = float(input("Enter speed in km/h: "))
        mph = kmh * 0.621371
        print(f"{kmh} km/h is equal to {mph:.2f} mph")
        return mph
    elif choice == "2":
        mph = float(input("Enter speed in mph: "))
        kmh = mph / 0.621371
        print(f"{mph} mph is equal to {kmh:.2f} km/h")
        return kmh
    else:
        print("Invalid choice. Please enter 1 or 2.")
        return None

speed_converter()

Choose conversion type:
1. km/h to mph
2. mph to km/h
Enter 1 or 2: 1
Enter speed in km/h: 35
35.0 km/h is equal to 21.75 mph


21.747985

## 3.7 – Global Variable

In [ ]:
score = 100

def print_global():
    print(score)

print_global()

100


## 3.7 – Local Variable

In [ ]:
def print_local():
    z = 42
    print(z)

print_local()

42


## 3.7 – Modifying a Global Variable

In [ ]:
score = 100

def modify_global():
    global score
    score = 250

modify_global()
print(score)

250


## 3.8 – try-except

In [ ]:
try:
    num = int(input("Enter a number: "))
    print("Result:", 20 / num)
except ZeroDivisionError:
    print("Cannot divide by zero.")
except ValueError:
    print("Invalid input. Please enter a number.")

Enter a number: 25
Result: 0.8


## 3.8 – finally Block

In [ ]:
try:
    file = open("data.txt", "r")
    data = file.read()
except FileNotFoundError:
    print("File not found.")
finally:
    print("Cleanup complete.")

File not found.
Cleanup complete.


## 3.8 – Raising Custom Exceptions

In [ ]:
def check_score(score):
    if score > 100:
        raise ValueError("Score cannot exceed 100.")
    else:
        print("Valid score")

try:
    check_score(150)
except ValueError as e:
    print(e)

Score cannot exceed 100.


## 6.1 – Importing NumPy and Creating a Zeros Array

In [ ]:
import numpy as np

zeros_arr = np.zeros((3, 4))
print("A zeros array is\n", zeros_arr, "with dimensions", zeros_arr.shape)

A zeros array is
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] with dimensions (3, 4)


## 6.1 – Creating Zero, One, and Multi-Dimensional Arrays

In [ ]:
import numpy as np

zero_dim_array = np.array(9)
one_dim_array = np.array([4, 5, 6, 7])
n_dim_array = np.array([[2, 4], [6, 8], [10, 12]])

for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
9
Dimension: 0
Data type: int64

Array:
[4 5 6 7]
Dimension: 1
Data type: int64

Array:
[[ 2  4]
 [ 6  8]
 [10 12]]
Dimension: 2
Data type: int64



## 6.1.1 – ndarray Attributes

In [ ]:
import numpy as np

arr_1d = np.array([2, 4, 6, 8, 10, 12])
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
arr_3d = np.array([[[2, 4, 6],
                    [8, 10, 12]],
                   [[14, 16, 18],
                    [20, 22, 24]]])

print(arr_1d.ndim)   # 1
print(arr_2d.ndim)   # 2
print(arr_3d.ndim)   # 3

print(arr_1d.shape)  # (6,)
print(arr_2d.shape)  # (2, 3)
print(arr_3d.shape)  # (2, 2, 3)

print(arr_1d.size)   # 6
print(arr_2d.size)   # 6
print(arr_3d.size)   # 12

print(arr_1d.dtype)
arr_float = np.array([2.2, 4.4, 6.6])
print(arr_float.dtype)

print(arr_1d.itemsize)
print(arr_1d.nbytes)

print(arr_2d.T)

for item in arr_2d.flat:
    print(item, end=" ")
print()

arr_complex = np.array([2+3j, 5+6j])
print(arr_complex.real)
print(arr_complex.imag)

arr_float2 = arr_2d.astype(float)
print(arr_float2)

1
2
3
(6,)
(2, 3)
(2, 2, 3)
6
6
12
int64
float64
8
48
[[10 40]
 [20 50]
 [30 60]]
10 20 30 40 50 60 
[2. 5.]
[3. 6.]
[[10. 20. 30.]
 [40. 50. 60.]]


## 6.1.2 – Common Errors with Key Attributes

In [ ]:
import numpy as np


lst = [[2, 4], [6, 8]]
arr = np.array(lst)
print(arr.shape)


arr = np.array([10, 20, 30])
if len(arr.shape) > 1:
    print(arr.shape[1])

# TypeError fix
arr = np.array([[2, 4, 6], [8, 10, 12]])
print(arr.shape)  # Correct

a = np.array([[2, 4], [6, 8]])
b = np.array([1, 2, 3])
try:
    print(a + b)
except ValueError as e:
    print(f"Error: {e}")

# MemoryError example
# large_array = np.ones((200000, 200000))

(2, 2)
(2, 3)
Error: operands could not be broadcast together with shapes (2,2) (3,) 


## 6.1.3 – reshape

In [ ]:
import numpy as np

array = np.array([[2, 4, 6],
                  [8, 10, 12]])

reshaped_array = array.reshape(3, 2)
print("Original Shape:", array.shape)
print("Reshaped Shape:", reshaped_array.shape)

# ValueError example
try:
    bad = array.reshape(5, 2)
except ValueError as e:
    print(f"Error: {e}")

Original Shape: (2, 3)
Reshaped Shape: (3, 2)
Error: cannot reshape array of size 6 into shape (5,2)


## 7 – arange

In [ ]:
import numpy as np

a = np.arange(2, 20)
print(a)

x = np.arange(5.7)
print(x)

x = np.arange(1.0, 12.5, 1.5)
print(x)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0. 1. 2. 3. 4. 5.]
[ 1.   2.5  4.   5.5  7.   8.5 10.  11.5]


## 7 – linspace

In [ ]:
import numpy as np

print(np.linspace(0, 5))
print(np.linspace(0, 5, 9))
print(np.linspace(0, 5, 9, endpoint=False))

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]
[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375 5.   ]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444]


## 7 – ones, zeros, empty, eye

In [ ]:
import numpy as np

ones_array = np.ones((3, 4))
zeros_array = np.zeros((4, 3))
empty_array = np.empty((3, 3))
identity_matrix = np.eye(4)

print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0.         0.55555556 1.11111111]
 [1.66666667 2.22222222 2.77777778]
 [3.33333333 3.88888889 4.44444444]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 7 – np.array from list/tuple/nested list

In [ ]:
import numpy as np

array_from_list = np.array([7, 8, 9])
array_from_tuple = np.array((10, 11, 12))
array_from_nested_list = np.array([[7, 8, 9], [10, 11, 12]])

print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n')

[7 8 9]
[10 11 12]
[[ 7  8  9]
 [10 11 12]]


## 7 – Arrays from existing shape

In [ ]:
import numpy as np

arr = np.array([[5, 6, 7], [8, 9, 10]])
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape)
print(arr, zeros, ones, empty, sep='\n')

[[ 5  6  7]
 [ 8  9 10]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6.89206560e-310 4.68640585e-315 1.99776275e+161]
 [1.22183298e+224 5.98186824e-154 9.57484973e+247]]


## 7 – hstack, vstack, column_stack

In [ ]:
import numpy as np

arr1 = np.array([[2, 4], [6, 8]])
arr2 = np.array([[10, 12], [14, 16]])

hstacked = np.hstack((arr1, arr2))
vstacked = np.vstack((arr1, arr2))
colstacked = np.column_stack((arr1[0], arr2[0]))

print(hstacked, vstacked, colstacked, sep='\n')

[[ 2  4 10 12]
 [ 6  8 14 16]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
[[ 2 10]
 [ 4 12]]


## 7 – concatenate (3D)

In [ ]:
import numpy as np

arr1 = np.array([[[2], [4]], [[6], [8]]])
arr2 = np.array([[[10], [12]], [[14], [16]]])

concat_axis0 = np.concatenate((arr1, arr2), axis=0)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
concat_axis2 = np.concatenate((arr1, arr2), axis=2)

print("axis 0:\n", concat_axis0, concat_axis0.shape)
print("axis 1:\n", concat_axis1, concat_axis1.shape)
print("axis 2:\n", concat_axis2, concat_axis2.shape)

axis 0:
 [[[ 2]
  [ 4]]

 [[ 6]
  [ 8]]

 [[10]
  [12]]

 [[14]
  [16]]] (4, 2, 1)
axis 1:
 [[[ 2]
  [ 4]
  [10]
  [12]]

 [[ 6]
  [ 8]
  [14]
  [16]]] (2, 4, 1)
axis 2:
 [[[ 2 10]
  [ 4 12]]

 [[ 6 14]
  [ 8 16]]] (2, 2, 2)


## 7.2 – Dimension Mismatch Fix

In [ ]:
import numpy as np

arr1 = np.array([[2, 4], [6, 8]])
arr2 = np.array([10, 12])

try:
    hstacked = np.hstack((arr1, arr2))
except ValueError as e:
    print(f"Error: {e}")

arr2 = arr2.reshape(2, 1)
hstacked = np.hstack((arr1, arr2))
print(hstacked)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
[[ 2  4 10]
 [ 6  8 12]]


## 7.2 – Shape Misalignment Fix

In [ ]:
import numpy as np

arr1 = np.array([[2, 4, 6], [8, 10, 12]])
arr2 = np.array([[14, 16], [18, 20]])

try:
    hstacked = np.hstack((arr1, arr2))
except ValueError as e:
    print(f"Error: {e}")

arr2 = np.array([[14, 16, 18], [20, 22, 24]])
hstacked = np.hstack((arr1, arr2))
print(hstacked)

[[ 2  4  6 14 16 18]
 [ 8 10 12 20 22 24]]


## 7.2 – Inconsistent Data Types Fix

In [ ]:
import numpy as np
# Incorrect shapes
arr1 = np.array([[1, 2], [3, 4]]) # shape (2, 2)
arr2 = np.array([5, 6]) # shape (2,)
# Attempting horizontal stack
try:
  hstacked = np.hstack((arr1, arr2)) # Error due to dimension mismatch
except ValueError as e:
  print(f"Error: {e}")
# Solution: Reshape arr2 to match arr1’s dimensions
arr2 = np.array([5, 6]).reshape(2, 1) # shape (2, 1)
hstacked = np.hstack((arr1, arr2))
print(hstacked)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
[[1 2 5]
 [3 4 6]]


## 7.2 – Too Many Dimensions Fix

In [ ]:
import numpy as np

arr1 = np.array([[[2, 4], [6, 8]]])
arr2 = np.array([[10, 12], [14, 16]])

try:
    vstacked = np.vstack((arr1, arr2))
except ValueError as e:
    print(f"Error: {e}")

arr1 = arr1.reshape(2, 2)
vstacked = np.vstack((arr1, arr2))
print(vstacked)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


## 8 – Array Indexing and Slicing

In [ ]:
import numpy as np

array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(array[0, 2])    # 30 (first row, third column)
print(array[-1, -1])  # 90 (last row, last column)
print(array[0:2, 0:2])  # [[10, 20], [40, 50]]

30
90
[[10 20]
 [40 50]]


## 8.1 – Index Out of Bounds Error

In [ ]:
import numpy as np

array = np.array([[10, 20, 30], [40, 50, 60]])

try:
    print(array[3, 0])
except IndexError as e:
    print(f"Error: {e}")

Error: index 3 is out of bounds for axis 0 with size 2


## 9.1 – Universal Functions (ufuncs)

In [ ]:
import numpy as np

arr = np.array([4, 9, 16, 25])

cubed = np.power(arr, 3)
sqrt = np.sqrt(arr)

print(f"Cubed: {cubed}")
print(f"Square root: {sqrt}")

Cubed: [   64   729  4096 15625]
Square root: [2. 3. 4. 5.]


## 9.1 – Mathematical ufuncs

In [ ]:
import numpy as np

arr = np.array([1, 4, 9, 25])
angles = np.array([0, np.pi / 6, np.pi / 3])

cosine_values = np.cos(angles)
log_values = np.log(arr)

print("Cosines:", cosine_values)
print("Log values:", log_values)

Cosines: [1.        0.8660254 0.5      ]
Log values: [0.         1.38629436 2.19722458 3.21887582]


## 9.2 – np.linalg operations

In [ ]:
import numpy as np

A = np.array([[2, 3], [5, 7]])
B = np.array([[1, 4], [2, 6]])

product = np.dot(A, B)
det = np.linalg.det(A)
inverse = np.linalg.inv(A)
eigvals, eigvecs = np.linalg.eig(A)

print(f"Matrix Product:\n{product}")
print(f"Determinant: {det}")
print(f"Inverse:\n{inverse}")
print(f"Eigenvalues: {eigvals}\nEigenvectors:\n{eigvecs}")

Matrix Product:
[[ 8 26]
 [19 62]]
Determinant: -0.9999999999999987
Inverse:
[[-7.  3.]
 [ 5. -2.]]
Eigenvalues: [-0.10977223  9.10977223]
Eigenvectors:
[[-0.81797819 -0.38876264]
 [ 0.57524923 -0.92133794]]


## 9.3 – Valid Broadcasting (column match)

In [ ]:
import numpy as np

A = np.array([[2], [4], [6]])   # Shape (3,1)
B = np.array([5, 10, 15])       # Shape (3,)

C = A + B  # Result shape: (3,3)
print(C)

[[ 7 12 17]
 [ 9 14 19]
 [11 16 21]]


## 9.3 – Valid Broadcasting (row match)

In [ ]:
import numpy as np

A = np.array([[2, 4, 6]])    # Shape (1,3)
B = np.array([[1], [2], [3]])  # Shape (3,1)

C = A + B  # Result shape: (3,3)
print(C)

[[3 5 7]
 [4 6 8]
 [5 7 9]]


## 9.3 – Invalid Broadcasting

In [ ]:
import numpy as np

A = np.ones((4, 2))
B = np.ones((2, 4))

try:
    C = A + B
except ValueError as e:
    print(f"Error: {e}")

Error: operands could not be broadcast together with shapes (4,2) (2,4) 


## 9.4 – Vectorization Speed Comparison

In [ ]:
import numpy as np
import time

size = 10**6
a = np.random.rand(size)
b = np.random.rand(size)

# Loop
start_time = time.time()
result_loop = np.zeros(size)
for i in range(size):
    result_loop[i] = a[i] * b[i]
loop_time = time.time() - start_time
print(f"Loop Execution Time: {loop_time:.5f} seconds")

# Vectorized
start_time = time.time()
result_vectorized = a * b
vectorized_time = time.time() - start_time
print(f"Vectorized Execution Time: {vectorized_time:.5f} seconds")

speedup = loop_time / vectorized_time
print(f"Vectorization is approximately {speedup:.2f} times faster!")

Loop Execution Time: 0.58136 seconds
Vectorized Execution Time: 0.00489 seconds
Vectorization is approximately 118.89 times faster!


#Section 4: Python Exercises


##Task 1 – Unit Converter

In [ ]:
def convert_length(value, direction):
    """
    Converts between meters and feet.
    """
    if direction == 'm_to_ft':
        return value * 3.28084
    elif direction == 'ft_to_m':
        return value / 3.28084
    else:
        raise ValueError("Invalid direction for length conversion.")

def convert_weight(value, direction):
    """
    Converts between kilograms and pounds.
    """
    if direction == 'kg_to_lbs':
        return value * 2.20462
    elif direction == 'lbs_to_kg':
        return value / 2.20462
    else:
        raise ValueError("Invalid direction for weight conversion.")

def convert_volume(value, direction):
    """
    Converts between liters and gallons.
    """
    if direction == 'l_to_gal':
        return value * 0.264172
    elif direction == 'gal_to_l':
        return value / 0.264172
    else:
        raise ValueError("Invalid direction for volume conversion.")

def unit_converter():
    """Drives the unit converter program."""
    print("Choose conversion type:")
    print("1. Length  2. Weight  3. Volume")
    try:
        choice = int(input("Enter 1, 2, or 3: "))
        value = float(input("Enter value: "))
        if choice == 1:
            direction = input("Enter m_to_ft or ft_to_m: ")
            result = convert_length(value, direction)
        elif choice == 2:
            direction = input("Enter kg_to_lbs or lbs_to_kg: ")
            result = convert_weight(value, direction)
        elif choice == 3:
            direction = input("Enter l_to_gal or gal_to_l: ")
            result = convert_volume(value, direction)
        else:
            raise ValueError("Invalid choice.")
        print(f"Result: {result:.4f}")
    except ValueError as e:
        print(f"Error: {e}")

unit_converter()

Choose conversion type:
1. Length  2. Weight  3. Volume
Enter 1, 2, or 3: 2
Enter value: 23
Enter kg_to_lbs or lbs_to_kg: kg_to_lbs
Result: 50.7063


Task 2 – Math Operations on a List

In [ ]:
def compute_sum(numbers):
    """Returns the sum of a list of numbers."""
    return sum(numbers)

def compute_average(numbers):
    """Returns the average of a list of numbers."""
    if not numbers:
        raise ValueError("List is empty.")
    return sum(numbers) / len(numbers)

def compute_maximum(numbers):
    """Returns the maximum value in a list."""
    if not numbers:
        raise ValueError("List is empty.")
    return max(numbers)

def compute_minimum(numbers):
    """Returns the minimum value in a list."""
    if not numbers:
        raise ValueError("List is empty.")
    return min(numbers)

def math_operations():
    """Drives the math operations program."""
    print("Choose an operation: 1. Sum  2. Average  3. Maximum  4. Minimum")
    try:
        choice = int(input("Enter 1-4: "))
        raw = input("Enter numbers separated by spaces: ")
        numbers = [float(x) for x in raw.split()]
        if not numbers:
            raise ValueError("No numbers entered.")
        ops = {1: compute_sum, 2: compute_average, 3: compute_maximum, 4: compute_minimum}
        if choice not in ops:
            raise ValueError("Invalid choice.")
        print(f"Result: {ops[choice](numbers)}")
    except ValueError as e:
        print(f"Error: {e}")

math_operations()

Choose an operation: 1. Sum  2. Average  3. Maximum  4. Minimum
Enter 1-4: 2
Enter numbers separated by spaces: 34 56
Result: 45.0


## 4.2 List Manipulation

In [ ]:
def extract_every_other(lst):
    """Returns every other element starting from index 0."""
    return lst[::2]

# Example usage:
print(f"[1, 2, 3, 4, 5, 6] -> {extract_every_other([1, 2, 3, 4, 5, 6])}")

[1, 2, 3, 4, 5, 6] -> [1, 3, 5]


In [ ]:
def get_sublist(lst, start, end):
    """Returns sublist from start to end inclusive."""
    return lst[start:end + 1]

# Example usage:
print(f"[1,2,3,4,5,6], start=2, end=4 -> {get_sublist([1,2,3,4,5,6], 2, 4)}")

[1,2,3,4,5,6], start=2, end=4 -> [3, 4, 5]


In [ ]:
def reverse_list(lst):
    """Returns the list reversed using slicing."""
    return lst[::-1]

# Example usage:
print(f"[1, 2, 3, 4, 5] -> {reverse_list([1, 2, 3, 4, 5])}")

[1, 2, 3, 4, 5] -> [5, 4, 3, 2, 1]


In [ ]:
def remove_first_last(lst):
    """Returns the list without the first and last elements."""
    return lst[1:-1]

# Example usage:
print(f"[1, 2, 3, 4, 5] -> {remove_first_last([1, 2, 3, 4, 5])}")

[1, 2, 3, 4, 5] -> [2, 3, 4]


In [ ]:
def get_first_n(lst, n):
    """Returns the first n elements."""
    return lst[:n]

# Example usage:
print(f"[1, 2, 3, 4, 5], n=3 -> {get_first_n([1, 2, 3, 4, 5], 3)}")

[1, 2, 3, 4, 5], n=3 -> [1, 2, 3]


In [ ]:
def get_last_n(lst, n):
    """Returns the last n elements."""
    return lst[-n:]

# Example usage:
print(f"[1, 2, 3, 4, 5], n=2 -> {get_last_n([1, 2, 3, 4, 5], 2)}")

[1, 2, 3, 4, 5], n=2 -> [4, 5]


In [ ]:
def reverse_skip(lst):
    """Returns every second element starting from second-to-last, going backward."""
    return lst[-2::-2]

# Example usage:
print(f"[1, 2, 3, 4, 5, 6] -> {reverse_skip([1, 2, 3, 4, 5, 6])}")

[1, 2, 3, 4, 5, 6] -> [5, 3, 1]


## 4.3 Nested Lists

In [ ]:
def flatten(lst):
    """Flattens a one-level nested list."""
    return [item for sublist in lst for item in sublist]

# Example usage:
print(f"[[1,2],[3,4],[5]] -> {flatten([[1,2],[3,4],[5]])}")

[[1,2],[3,4],[5]] -> [1, 2, 3, 4, 5]


In [ ]:
def access_nested_element(lst, indices):
    """Returns the element at the position given by indices."""
    result = lst
    for i in indices:
        result = result[i]
    return result

# Example usage:
lst_nested = [[1,2,3],[4,5,6],[7,8,9]]
indices_nested = [1,2]
print(f"lst={lst_nested}, indices={indices_nested} -> {access_nested_element(lst_nested, indices_nested)}")

lst=[[1, 2, 3], [4, 5, 6], [7, 8, 9]], indices=[1, 2] -> 6


In [ ]:
def sum_nested(lst):
    """Recursively sums all elements in a nested list."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

# Example usage:
print(f"[[1,2],[3,[4,5]],6] -> {sum_nested([[1,2],[3,[4,5]],6])}")

[[1,2],[3,[4,5]],6] -> 21


In [ ]:
def remove_element(lst, elem):
    """Removes all occurrences of elem from a nested list."""
    return [
        remove_element(item, elem) if isinstance(item, list) else item
        for item in lst if item != elem
    ]

# Example usage:
print(f"[[1,2],[3,2],[4,5]], elem=2 -> {remove_element([[1,2],[3,2],[4,5]], 2)}")

[[1,2],[3,2],[4,5]], elem=2 -> [[1], [3], [4, 5]]


In [ ]:
def find_max(lst):
    """Finds the maximum element in a nested list of any depth."""
    flat = []
    def helper(l):
        for item in l:
            helper(item) if isinstance(item, list) else flat.append(item)
    helper(lst)
    return max(flat)

# Example usage:
print(f"[[1,2],[3,[4,5]],6] -> {find_max([[1,2],[3,[4,5]],6])}")

[[1,2],[3,[4,5]],6] -> 6


In [ ]:
def count_occurrences(lst, elem):
    """Counts occurrences of elem in a nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

# Example usage:
print(f"[[1,2],[2,3],[2,4]], elem=2 -> {count_occurrences([[1,2],[2,3],[2,4]], 2)}")

[[1,2],[2,3],[2,4]], elem=2 -> 3


In [ ]:
def deep_flatten(lst):
    """Flattens a deeply nested list to any depth."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

# Example usage:
print(f"[[[1,2],[3,4]],[[5,6],[7,8]]] -> {deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]])}")

[[[1,2],[3,4]],[[5,6],[7,8]]] -> [1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
def average_nested(lst):
    """Returns the average of all elements in a nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

# Example usage:
print(f"[[1,2],[3,4],[5,6]] -> {average_nested([[1,2],[3,4],[5,6]])}")

[[1,2],[3,4],[5,6]] -> 3.5


## Section 10: NumPy Exercises

### Problem 1 – Array Creation

In [ ]:
import numpy as np

empty_arr = np.empty((2, 2))
print(f"Empty array:\n{empty_arr}\n")

ones_arr = np.ones((4, 2))
print(f"Ones array:\n{ones_arr}\n")

full_arr = np.full((3, 3), 7)
print(f"Full array (filled with 7):\n{full_arr}\n")

ref = np.array([[1, 2], [3, 4]])
zeros_like_arr = np.zeros_like(ref)
print(f"Zeros like ref array:\n{zeros_like_arr}\n")

ones_like_arr = np.ones_like(ref)
print(f"Ones like ref array:\n{ones_like_arr}\n")

new_list = [1, 2, 3, 4]
arr = np.array(new_list)
print(f"Array from list:\n{arr}\n")

Empty array:
[[4.69351771e-315 0.00000000e+000]
 [6.89206345e-310 5.77904633e-317]]

Ones array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array (filled with 7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like ref array:
[[0 0]
 [0 0]]

Ones like ref array:
[[1 1]
 [1 1]]

Array from list:
[1 2 3 4]



### Problem 2 – Numerical Ranges and Indexing

In [ ]:
import numpy as np

# 1. Values 10 to 49
arr = np.arange(10, 50)
print(f"Array with values 10 to 49:\n{arr}\n")

# 2. 3x3 matrix, values 0–8
matrix = np.arange(9).reshape(3, 3)
print(f"3x3 matrix with values 0-8:\n{matrix}\n")

# 3. 3x3 identity matrix
identity = np.eye(3)
print(f"3x3 identity matrix:\n{identity}\n")

# 4. Random array size 30, find mean
rand_arr = np.random.random(30)
print(f"Random array (size 30):\n{rand_arr[:5]}...\nMean: {rand_arr.mean():.4f}\n")

# 5. 10x10 random array, min and max
big_arr = np.random.random((10, 10))
print(f"10x10 random array (first 2 rows):\n{big_arr[:2]}\nMin: {big_arr.min():.4f}, Max: {big_arr.max():.4f}\n")

# 6. Zero array size 10, replace 5th element with 1
z = np.zeros(10)
z[4] = 1
print(f"Zero array with 5th element replaced:\n{z}\n")

# 7. Reverse an array
arr_rev = np.array([1, 2, 0, 0, 4, 0])
print(f"Original array for reverse: {arr_rev}\nReversed array: {arr_rev[::-1]}\n")

# 8. 2D array with 1 on border and 0 inside
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print(f"2D array with 1 on border and 0 inside:\n{border_arr}\n")

# 9. 8x8 checkerboard pattern
checker = np.zeros((8, 8), dtype=int)
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print(f"8x8 checkerboard pattern:\n{checker}\n")

Array with values 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix with values 0-8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array (size 30):
[0.05360098 0.19850708 0.36950794 0.75123708 0.02942831]...
Mean: 0.5386

10x10 random array (first 2 rows):
[[0.43035298 0.60689342 0.01473129 0.61804528 0.17384359 0.03212138
  0.5582138  0.19119611 0.64706439 0.07134234]
 [0.42263729 0.95128985 0.86985937 0.00343932 0.65459509 0.22554972
  0.96106069 0.62602495 0.78894745 0.58962591]]
Min: 0.0027, Max: 0.9959

Zero array with 5th element replaced:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Original array for reverse: [1 2 0 0 4 0]
Reversed array: [0 4 0 0 2 1]

2D array with 1 on border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

8x8 checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [

### Problem 3 – Array Operations

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print(f"x:\n{x}\n")
print(f"y:\n{y}\n")
print(f"v:\n{v}\n")
print(f"w:\n{w}\n")

print(f"x + y (Add):\n{x + y}\n")
print(f"x - y (Subtract):\n{x - y}\n")
print(f"x * 3 (Multiply by integer):\n{x * 3}\n")
print(f"x ** 2 (Square each element):\n{x ** 2}\n")

print(f"np.dot(v, w) (dot: v and w -> scalar): {np.dot(v, w)}\n")
print(f"np.dot(x, v) (dot: x and v -> 1D array): {np.dot(x, v)}\n")
print(f"np.dot(x, y) (dot: x and y -> 2D array):\n{np.dot(x, y)}\n")

# Concatenate x and y along rows
print(f"Concatenate x and y along rows (np.vstack):\n{np.vstack((x, y))}\n")

# Concatenate v and w as columns
print(f"Concatenate v and w as columns (np.column_stack):\n{np.column_stack((v, w))}\n")

# Concatenate x and v — this raises a ValueError if not reshaped:
# x is shape (2,2) and v is shape (2,) — different number of dimensions.
# NumPy can't concatenate a 2D and 1D array directly along any axis without reshaping.
# Fix:
print(f"Concatenate x (2D) and reshaped v (1D) along rows:\n{np.concatenate((x, v.reshape(1, 2)), axis=0)}\n")

x:
[[1 2]
 [3 5]]

y:
[[5 6]
 [7 8]]

v:
[ 9 10]

w:
[11 12]

x + y (Add):
[[ 6  8]
 [10 13]]

x - y (Subtract):
[[-4 -4]
 [-4 -3]]

x * 3 (Multiply by integer):
[[ 3  6]
 [ 9 15]]

x ** 2 (Square each element):
[[ 1  4]
 [ 9 25]]

np.dot(v, w) (dot: v and w -> scalar): 219

np.dot(x, v) (dot: x and v -> 1D array): [29 77]

np.dot(x, y) (dot: x and y -> 2D array):
[[19 22]
 [50 58]]

Concatenate x and y along rows (np.vstack):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w as columns (np.column_stack):
[[ 9 11]
 [10 12]]

Concatenate x (2D) and reshaped v (1D) along rows:
[[ 1  2]
 [ 3  5]
 [ 9 10]]



### Problem 4 – Matrix Operations

In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

print(f"Matrix A:\n{A}\n")
print(f"Matrix B:\n{B}\n")

# 1. Prove A * A_inv = I
A_inv = np.linalg.inv(A)
print(f"Inverse of A:\n{A_inv}\n")
print(f"A * A_inv (should be identity matrix):\n{np.round(np.dot(A, A_inv))}\n")

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print(f"AB:\n{AB}\n")
print(f"BA:\n{BA}\n")
print(f"AB == BA?: {np.array_equal(AB, BA)}\n")

# 3. Prove (AB)^T = B^T * A^T
print(f"(AB)^T:\n{np.dot(A, B).T}\n")
print(f"B^T * A^T:\n{np.dot(B.T, A.T)}\n")
print(f"(AB)^T == B^T * A^T?: {np.array_equal(np.dot(A, B).T, np.dot(B.T, A.T))}\n")

# Solve system of linear equations
# 2x - 3y + z = -1
# x  - y + 2z = -3
# 3x + y  - z =  9
A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]], dtype=float)
b_sys = np.array([-1, -3, 9], dtype=float)

print(f"System Matrix A:\n{A_sys}\n")
print(f"System Vector b:\n{b_sys}\n")

# Method 1: Inverse method
X_inv = np.dot(np.linalg.inv(A_sys), b_sys)
print(f"Solution using inverse method: x={X_inv[0]:.2f}, y={X_inv[1]:.2f}, z={X_inv[2]:.2f}\n")

# Method 2: np.linalg.solve
X_solve = np.linalg.solve(A_sys, b_sys)
print(f"Solution using np.linalg.solve: x={X_solve[0]:.2f}, y={X_solve[1]:.2f}, z={X_solve[2]:.2f}\n")

Matrix A:
[[3 4]
 [7 8]]

Matrix B:
[[5 3]
 [2 1]]

Inverse of A:
[[-2.    1.  ]
 [ 1.75 -0.75]]

A * A_inv (should be identity matrix):
[[1. 0.]
 [0. 1.]]

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

AB == BA?: False

(AB)^T:
[[23 51]
 [13 29]]

B^T * A^T:
[[23 51]
 [13 29]]

(AB)^T == B^T * A^T?: True

System Matrix A:
[[ 2. -3.  1.]
 [ 1. -1.  2.]
 [ 3.  1. -1.]]

System Vector b:
[-1. -3.  9.]

Solution using inverse method: x=2.00, y=1.00, z=-2.00

Solution using np.linalg.solve: x=2.00, y=1.00, z=-2.00



## 10.2 Experiment: How Fast is NumPy?

In [ ]:
import numpy as np
import time

SIZE = 1_000_000

list_a = list(range(SIZE))
list_b = list(range(SIZE))
np_a = np.arange(SIZE, dtype=float)
np_b = np.arange(SIZE, dtype=float)

print(f"Comparing operations for {SIZE} elements:\n")

# 1. Element-wise Addition
t = time.time()
_ = [list_a[i] + list_b[i] for i in range(SIZE)]
print(f"List add:   {time.time()-t:.4f}s")
t = time.time()
_ = np_a + np_b
print(f"NumPy add:  {time.time()-t:.4f}s\n")

# 2. Element-wise Multiplication
t = time.time()
_ = [list_a[i] * list_b[i] for i in range(SIZE)]
print(f"List mul:   {time.time()-t:.4f}s")
t = time.time()
_ = np_a * np_b
print(f"NumPy mul:  {time.time()-t:.4f}s\n")

# 3. Dot Product
t = time.time()
_ = sum(list_a[i]*list_b[i] for i in range(SIZE))
print(f"List dot:   {time.time()-t:.4f}s")
t = time.time()
_ = np.dot(np_a, np_b)
print(f"NumPy dot:  {time.time()-t:.4f}s\n")

# 4. Matrix Multiplication
MAT = 100
# For performance comparison, use a smaller matrix size if MAT=1000 causes OOM or very long execution.
# If MAT=1000 is intended for the prompt, comment out or adjust as necessary for Colab environment.
# The example in the original text used MAT=1000 but the time for list matmul was '%.2f's which implies a longer run.
mat_np = np.random.rand(MAT, MAT)
mat_list = mat_np.tolist()

print(f"Comparing matrix multiplication for {MAT}x{MAT} matrices:\n")
t = time.time()
_ = [[sum(mat_list[r][k]*mat_list[k][c] for k in range(MAT)) for c in range(MAT)] for r in range(MAT)]
print(f"List matmul:   {time.time()-t:.4f}s")

t = time.time()
_ = np.dot(mat_np, mat_np)
print(f"NumPy matmul:  {time.time()-t:.4f}s\n")

Comparing operations for 1000000 elements:

List add:   0.1199s
NumPy add:  0.0228s

List mul:   0.1332s
NumPy mul:  0.0226s

List dot:   0.1120s
NumPy dot:  0.0023s

Comparing matrix multiplication for 100x100 matrices:

List matmul:   0.2431s
NumPy matmul:  0.0031s

